<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Restaurant;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSalesByRestaurant(Restaurant $restaurant)
    {
        $qb = $this->createQueryBuilder('sl')
            ->select(
                'sl.id as id',
                'sl.name as name',
                'sl.startDate as startDate',
                'sl.endDate as endDate',
                'sl.sealLimit as sealLimit',
                'u.id as userId',
                'u.name as userName',
                'se.createdAt as sealCreatedAt'
            )
            ->leftJoin('sl.seals', 'se')
            ->leftJoin('se.user', 'u')
            ->where('sl.restaurant = :restaurant')
            ->setParameter('restaurant', $restaurant)
            ->orderBy('sl.startDate', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
