<?php

namespace AppBundle\Repository;

/**
 * SealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSealsByUserAndSale($user, $sale)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.user = :user')
            ->andWhere('s.sale = :sale')
            ->setParameters(['user' => $user, 'sale' => $sale]);

        return $qb->getQuery()->getResult();
    }
}
