# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    token.generator:
        class: AppBundle\Services\TokenGenerator

    app.notification:
        class: AppBundle\Services\Notification
        arguments: ['@doctrine.orm.entity_manager', '@service_container']


    extras.twig_extension:
        class: AppBundle\Twig\Extras
        arguments: ['@security.token_storage']
        tags:
            - { name: twig.extension }

